#!/bin/bash
desktops=$(bspc query -D --names) ##all desktops
binDesktop=$(bspc query --desktops)
newDesktop=$1

## Add new desktop if doesn't exist, focus if does ##
if [[ $desktops == *${newDesktop}* ]]; then
    bspc desktop -f $newDesktop
else
    bspc monitor -d $desktops $newDesktop
    bspc desktop -f $newDesktop
fi

## Remove empty desktops ##
oldDesktop=$(bspc query -D -d last)
numNodes=$(bspc query -N -d ${oldDesktop} | grep -f <(bspc query -N -n .leaf) | wc -l)
echo $numNodes
if [ $numNodes = "0" ]; then
    bspc desktop $oldDesktop --remove
fi
